language: scala
sudo: false
scala:
- 2.12.12
- 2.13.3
dist: xenial
jdk: openjdk8
script:
- sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck "++ ${TRAVIS_SCALA_VERSION}! -v" test
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.12
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
  - $HOME/.cache/coursier/v1
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
